Type: AWS::DynamoDB::Table
Properties:
  TableName: config_orgs
  AttributeDefinitions:
    - AttributeName: org
      AttributeType: S
    - AttributeName: name
      AttributeType: S
  KeySchema:
    - AttributeName: org
      KeyType: HASH
    - AttributeName: name
      KeyType: RANGE
  ProvisionedThroughput:
    ReadCapacityUnits: 200
    WriteCapacityUnits: 25
  StreamSpecification:
    StreamViewType: NEW_AND_OLD_IMAGES
